services:
  tunacd:
    container_name: tunacd
    image: ghcr.io/octoberserver/tunacd:latest
    # image: tunacd:latest
    # ports:
    #   - "8080:8080"
    environment:
      - AUTH_TOKEN=${HTTP_AUTH_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`tuna.octsrv.org`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
